### ISSUE TITLE
[Suggestion] Add a runtime label

### ISSUE THREAD

**Issue by cmoulliard** [gorkem/app-labels#3]
**Description**

The part-of, component, name and instance labels allow to describe, what the component, that we will deploy and part of an application is :  

| Part of  | Name | Component |  Instance |
|--------|-------------|------|-----------|
| accounting | purchase-order | frontend | po-123
| accounting | purchase-order | backend | po-567
| accounting | billing | frontend | bill-123
| accounting | general-ledger | integration | gl-123

but it does not help us to figure out which technology, framework, runtime it uses/consumes
and that we could use graphically within a Web console 

**Proposition**

In order to better document or display graphically what a component is, I would like to propose that we  add 2 annotations or labels to decorate the component with the information about what is the runtime/technology used and its version

**Definition**

**app.openshift.io/runtime**: bootstrapping framework used to start the application (E.g. Spring Boot, vert.x, Tornthail, Apache Tomcat, ...)
**app.openshift.io/version**: version of the runtime

Remark: To disambiguate the app version from the runtime version, then the version's label of the app should be renamed to `app.kubernetes.io/appversion`

Example

```
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/part-of: accounting
    app.kubernetes.io/name: purchase-order
    app.kubernetes.io/instance: po-123
    app.kubernetes.io/appversion: "1.0.1"
    app.kubernetes.io/component: frontend
    app.kubernetes.io/managed-by: component-operator
    app.openshift.io/runtime: spring-boot
    app.openshift.io/version: "1.5.17"
```

WDYT : @Steve, @gorkem, @tkral, @siamak ?
